### ISSUE TITLE
clogin error: Error: missing close-bracket

### ISSUE THREAD

**Issue by nickcolton** [mwallraf/ZenPacks.TwoNMS.Rancid#2]
Things seemed to be working fine as I ran the zenrancid plugin to check routers for a few hours.  For some reason I now am getting an error saying clogin error: Error: missing close-bracket.  I have uninstalled zenrancid completely, deleted any leftover files, deleted the zenpack and re-downloaded from git and after re-installing have the same error again.

**Comment by mwallraf** [comment]
Hi, did you install the latest tagged version from github or just latest available version? The tagged version should work fine but not 100% sure about later versions, still has to be tested further..

Otherwise try 'zenrancid run --device=<device> -v 20' and see if you get more info.

Maarten

**Comment by nickcolton** [comment]
I probably installed the latest available.  Still trying to figure out how git works.  I'll work on figuring out how to install the tagged version and see if that fixes.  Thanks!

**Comment by mwallraf** [comment]
There should be a button with all the branches and tags, just select the latest tag and download that zip, should be it.

Let me know if you cannot get it working, would be interesting to know what the problem is :)

**Comment by nickcolton** [comment]
Was able to get v1.0.0 installed, getting the same error. 

Here is the zenrancid command I'm running, below that is log output from the rancid log file.

[zenoss@opsview logs]$ zenrancid run --device=10.20.0.251 -v 20
2013-09-03 16:28:11,925 INFO zen.zenrancid: call init
2013-09-03 16:28:11,927 INFO zen.zenrancid: main_loop started in rancidd
2013-09-03 16:28:12,141 INFO zen.zenrancid: Starting Rancid for device 10.20.0.251
2013-09-03 16:28:12,822 INFO zen.rancidd: Daemon rancidd shutting down

[zenoss@opsview logs]$ 

starting: Tue Sep 3 16:25:22 MDT 2013

Trying to get all of the configs.
10.20.0.251 clogin error: Error: missing close-bracket
10.20.0.251: missed cmd(s): dir /all slavedisk2:,show rsp chassis-info,show capture,dir /all sec-slot2:,show diag,dir /all disk1:,show gsr chassis,dir /all sec-nvram:,show di
ag chassis-info,dir /all disk2:,show running-config view full,dir /all sec-bootflash:,show spe version,dir /all slaveslot2:,dir /all disk0:,show install active,show bootvar,d
ir /all slaveslot0:,dir /all sec-slot1:,dir /all harddiska:,dir /all slavenvram:,show flash,dir /all sec-disk2:,dir /all slavesup-bootflash:,dir /all sec-disk0:,dir /all hard
diskb:,show variables boot,show boot,show inventory raw,dir /all slavedisk1:,show env all,show module,show shun,show controllers,show diagbus,more system:running-config,dir /
all slavedisk0:,show debug,show idprom backplane,dir /all bootflash:,dir /all sup-bootdisk:,dir /all sec-slot0:,dir /all sec-disk1:,write term,show vtp status,dir /all sup-bo
otflash:,dir /all slot2:,dir /all harddisk:,dir /all slot0:,dir /all sup-microcode:,show vlan,dir /all slavebootflash:,show controllers cbus,dir /all slaveslot1:,dir /all nvr
am:,show version,show vlan-switch,show redundancy secondary,show running-config,show c7200,dir /all slot1:
10.20.0.251: End of run not found

# !

Getting missed routers: round 1.
10.20.0.251 clogin error: Error: missing close-bracket
10.20.0.251: missed cmd(s): dir /all slavedisk2:,show rsp chassis-info,show capture,dir /all sec-slot2:,show diag,dir /all disk1:,show gsr chassis,dir /all sec-nvram:,show di
ag chassis-info,dir /all disk2:,show running-config view full,dir /all sec-bootflash:,show spe version,dir /all slaveslot2:,dir /all disk0:,show install active,show bootvar,d
ir /all slaveslot0:,dir /all sec-slot1:,dir /all harddiska:,dir /all slavenvram:,show flash,dir /all sec-disk2:,dir /all slavesup-bootflash:,dir /all sec-disk0:,dir /all hard
diskb:,show variables boot,show boot,show inventory raw,dir /all slavedisk1:,show env all,show module,show shun,show controllers,show diagbus,more system:running-config,dir /
all slavedisk0:,show debug,show idprom backplane,dir /all bootflash:,dir /all sup-bootdisk:,dir /all sec-slot0:,dir /all sec-disk1:,write term,show vtp status,dir /all sup-bo
otflash:,dir /all slot2:,dir /all harddisk:,dir /all slot0:,dir /all sup-microcode:,show vlan,dir /all slavebootflash:,show controllers cbus,dir /all slaveslot1:,dir /all nvr
am:,show version,show vlan-switch,show redundancy secondary,show running-config,show c7200,dir /all slot1:
10.20.0.251: End of run not found

# !

Getting missed routers: round 2.
10.20.0.251 clogin error: Error: missing close-bracket
10.20.0.251: missed cmd(s): dir /all slavedisk2:,show rsp chassis-info,show capture,dir /all sec-slot2:,show diag,dir /all disk1:,show gsr chassis,dir /all sec-nvram:,show di
ag chassis-info,dir /all disk2:,show running-config view full,dir /all sec-bootflash:,show spe version,dir /all slaveslot2:,dir /all disk0:,show install active,show bootvar,d
ir /all slaveslot0:,dir /all sec-slot1:,dir /all harddiska:,dir /all slavenvram:,show flash,dir /all sec-disk2:,dir /all slavesup-bootflash:,dir /all sec-disk0:,dir /all hard
diskb:,show variables boot,show boot,show inventory raw,dir /all slavedisk1:,show env all,show module,show shun,show controllers,show diagbus,more system:running-config,dir /
all slavedisk0:,show debug,show idprom backplane,dir /all bootflash:,dir /all sup-bootdisk:,dir /all sec-slot0:,dir /all sec-disk1:,write term,show vtp status,dir /all sup-bo
otflash:,dir /all slot2:,dir /all harddisk:,dir /all slot0:,dir /all sup-microcode:,show vlan,dir /all slavebootflash:,show controllers cbus,dir /all slaveslot1:,dir /all nvr
am:,show version,show vlan-switch,show redundancy secondary,show running-config,show c7200,dir /all slot1:
10.20.0.251: End of run not found

# !

Getting missed routers: round 3.
10.20.0.251 clogin error: Error: missing close-bracket
10.20.0.251: missed cmd(s): dir /all slavedisk2:,show rsp chassis-info,show capture,dir /all sec-slot2:,show diag,dir /all disk1:,show gsr chassis,dir /all sec-nvram:,show di
ag chassis-info,dir /all disk2:,show running-config view full,dir /all sec-bootflash:,show spe version,dir /all slaveslot2:,dir /all disk0:,show install active,show bootvar,d
ir /all slaveslot0:,dir /all sec-slot1:,dir /all harddiska:,dir /all slavenvram:,show flash,dir /all sec-disk2:,dir /all slavesup-bootflash:,dir /all sec-disk0:,dir /all hard
diskb:,show variables boot,show boot,show inventory raw,dir /all slavedisk1:,show env all,show module,show shun,show controllers,show diagbus,more system:running-config,dir /
all slavedisk0:,show debug,show idprom backplane,dir /all bootflash:,dir /all sup-bootdisk:,dir /all sec-slot0:,dir /all sec-disk1:,write term,show vtp status,dir /all sup-bo
otflash:,dir /all slot2:,dir /all harddisk:,dir /all slot0:,dir /all sup-microcode:,show vlan,dir /all slavebootflash:,show controllers cbus,dir /all slaveslot1:,dir /all nvr
am:,show version,show vlan-switch,show redundancy secondary,show running-config,show c7200,dir /all slot1:
10.20.0.251: End of run not found

# !

Getting missed routers: round 4.
10.20.0.251 clogin error: Error: missing close-bracket
10.20.0.251: missed cmd(s): dir /all slavedisk2:,show rsp chassis-info,show capture,dir /all sec-slot2:,show diag,dir /all disk1:,show gsr chassis,dir /all sec-nvram:,show di
ag chassis-info,dir /all disk2:,show running-config view full,dir /all sec-bootflash:,show spe version,dir /all slaveslot2:,dir /all disk0:,show install active,show bootvar,d
ir /all slaveslot0:,dir /all sec-slot1:,dir /all harddiska:,dir /all slavenvram:,show flash,dir /all sec-disk2:,dir /all slavesup-bootflash:,dir /all sec-disk0:,dir /all hard
diskb:,show variables boot,show boot,show inventory raw,dir /all slavedisk1:,show env all,show module,show shun,show controllers,show diagbus,more system:running-config,dir /
all slavedisk0:,show debug,show idprom backplane,dir /all bootflash:,dir /all sup-bootdisk:,dir /all sec-slot0:,dir /all sec-disk1:,write term,show vtp status,dir /all sup-bo
otflash:,dir /all slot2:,dir /all harddisk:,dir /all slot0:,dir /all sup-microcode:,show vlan,dir /all slavebootflash:,show controllers cbus,dir /all slaveslot1:,dir /all nvr
am:,show version,show vlan-switch,show redundancy secondary,show running-config,show c7200,dir /all slot1:
10.20.0.251: End of run not found
!

ending: Tue Sep 3 16:25:22 MDT 2013

**Comment by mwallraf** [comment]
Do you have any special chars in your password or username? If so then try escaping them with backslash or try with a simple password first, just to be sure

**Comment by nickcolton** [comment]
Looks like it was just a special char in my password.  Ended up having to remove all local settings from each device, setting the username/password at a higher level without the special character and then re-enabling zenrancid on devices.

Thanks again for the help and I appreciate the zenpack!

**Comment by mwallraf** [comment]
Escaping the special characters in the password with  \ should also do the trick : 

example:  My pa$$ => My\ pa\$\$

Not sure though if it will work with all special characters.
